FROM php:8.2-fpm

# # Install dependencies PHP & Nginx
# RUN apt-get update && apt-get install -y \
#     nginx \
#     zip unzip git curl libpng-dev libonig-dev libxml2-dev libzip-dev \
#     nodejs npm \
#     && docker-php-ext-install pdo_mysql zip \
#     && apt-get clean && rm -rf /var/lib/apt/lists/*

RUN apt-get update && apt-get install -y \
    zip unzip git curl libpng-dev libonig-dev libxml2-dev libzip-dev \
    nodejs npm \
    && docker-php-ext-install pdo_mysql zip \
    && apt-get clean && rm -rf /var/lib/apt/lists/*

# Install Composer
COPY --from=composer:latest /usr/bin/composer /usr/bin/composer

WORKDIR /var/www

COPY . .

RUN composer install --optimize-autoloader --no-dev

RUN php artisan storage:link

# Build frontend assets jika perlu
RUN npm install && npm run build

# # Copy konfigurasi nginx ke folder yang benar
# COPY ./nginx/nginx.conf /etc/nginx/conf.d/default.conf

COPY ./nginx/nginx.conf /etc/nginx/conf.d/default.conf

# Expose port 80 untuk nginx
EXPOSE 80

# # Jalankan nginx & php-fpm secara bersamaan dengan supervisord (lebih baik)
# RUN apt-get update && apt-get install -y supervisor && apt-get clean && rm -rf /var/lib/apt/lists/*

# COPY ./supervisord.conf /etc/supervisor/conf.d/supervisord.conf

# CMD ["supervisord", "-n"]

CMD ["php-fpm"]
