apiVersion: apps/v1
kind: Deployment
metadata:
  name: laravel-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: laravel
  template:
    metadata:
      labels:
        app: laravel
    spec:
      initContainers:
        - name: copy-app-code
          image: meetthechef-app:latest
          imagePullPolicy: IfNotPresent
          command: ["sh", "-c", "cp -r /var/www/html/. /app-code"]
          volumeMounts:
            - name: app-code
              mountPath: /app-code

      containers:
        - name: php-fpm
          image: meetthechef-app:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 9000
          envFrom:
            - configMapRef:
                name: laravel-config
            - secretRef:
                name: laravel-secret
          volumeMounts:
            - name: app-code
              mountPath: /var/www/html
            - name: storage
              mountPath: /var/www/html/storage

        - name: nginx
          image: nginx:stable-alpine
          ports:
            - containerPort: 80
          volumeMounts:
            - name: app-code
              mountPath: /var/www/html
            - name: storage
              mountPath: /var/www/html/storage
              readOnly: true
            - name: nginx-config
              mountPath: /etc/nginx/conf.d/default.conf
              subPath: default.conf

      volumes:
        - name: app-code
          emptyDir: {}
        - name: storage
          persistentVolumeClaim:
            claimName: laravel-storage-pvc
        - name: nginx-config
          configMap:
            name: nginx-config
